#! /bin/sh

bspc config focus_follows_pointer true

bspc config border_width        2
bspc config window_gap         24
bspc config right_padding     120

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc monitor -d I II III IV V VI VII VIII IX X

compton --config $HOME/.config/compton/compton.conf -b
conky &
#sxhkd &
trayer --edge bottom --align right --height 24 --width 300 --heighttype pixel --widthtype pixel --transparent true --alpha 255 --tint 0x0a0b09 &
nitrogen --restore &
