;; If not installed already, install cask via:
;; curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
(source gnu)
(source melpa)
(source marmalade)
(source org)

;; Auto-added
(depends-on "f")
(depends-on "s")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "smex")
(depends-on "use-package")

;; Makes the environment usable
(depends-on "avy")
(depends-on "aggressive-indent")
(depends-on "counsel")
(depends-on "company")
(depends-on "ido-vertical-mode")
(depends-on "ido-ubiquitous")
(depends-on "multiple-cursors")
(depends-on "rainbow-delimiters")
(depends-on "smartparens")
(depends-on "swiper")
(depends-on "undo-tree")

;; Programming extensions
(depends-on "cider")
(depends-on "clj-refactor")
(depends-on "clojure-mode-extra-font-locking")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "origami")
(depends-on "parinfer")
(depends-on "web-mode")
(depends-on "yasnippet")

;; Additional functionality
(depends-on "org")
(depends-on "which-key")
(depends-on "circe")

;; Themes
(depends-on "monokai-theme")
(depends-on "leuven-theme")
(depends-on "emojify")

